// Copyright (c) 2025-2026 Zensical and contributors

// SPDX-License-Identifier: MIT
// All contributions are certified under the DCO

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

// ----------------------------------------------------------------------------

//! Feed artifact construction and shared feed URLs.

use anyhow::Result;
use zrx::id::Id;
use zrx::stream::Key;

use crate::config::plugins::RssPluginConfig;
use crate::config::Project;
use crate::path::{SitePath, SourceRoot};
use crate::structure::page::PageOrigin;
use crate::workflow::output::Artifact;

use super::{candidate_key, Entry, Stamp};

mod item;
mod json;
mod xml;

// ----------------------------------------------------------------------------
// Functions
// ----------------------------------------------------------------------------

/// Emits the enabled feed variants and their shared stylesheet.
// Keep borrowed input slices and settings separate without allocating a context.
#[allow(clippy::too_many_arguments)]
pub fn artifacts(
    project: &Project, docs: &SourceRoot, settings: &RssPluginConfig,
    instance: usize, emit_stylesheet: bool, created: &[Entry],
    updated: &[Entry], now: &Stamp,
) -> Result<Vec<(Key<Id>, Artifact)>> {
    let mut output = Vec::new();
    let variants = [
        (
            "created",
            created,
            &settings.feeds_filenames.rss_created,
            &settings.feeds_filenames.json_created,
        ),
        (
            "updated",
            updated,
            &settings.feeds_filenames.rss_updated,
            &settings.feeds_filenames.json_updated,
        ),
    ];
    for (kind, entries, rss_name, json_name) in variants {
        if settings.rss_feed_enabled {
            let bytes = xml::render(
                project, docs, settings, rss_name, entries, kind, now,
            )?;
            output.push(artifact(instance, rss_name, bytes.into_bytes())?);
        }
        if settings.json_feed_enabled {
            let value =
                json::render(project, docs, settings, json_name, entries, now)?;
            let bytes = if settings.pretty_print {
                serde_json::to_vec_pretty(&value)?
            } else {
                serde_json::to_vec(&value)?
            };
            output.push(artifact(instance, json_name, bytes)?);
        }
    }
    if emit_stylesheet {
        output.push(artifact(
            instance,
            "rss.xsl",
            include_bytes!("default.xsl").to_vec(),
        )?);
    }
    Ok(output)
}

/// Wraps generated bytes with their stable output identity.
fn artifact(
    instance: usize, name: &str, contents: Vec<u8>,
) -> Result<(Key<Id>, Artifact)> {
    let destination: SitePath = name.parse()?;
    Ok((
        candidate_key("rss-output", instance, name),
        Artifact::page(
            PageOrigin::Generated {
                identity: format!("rss:{instance}:{name}"),
                provenance: None,
            },
            destination,
            contents,
        ),
    ))
}

/// Returns the site URL with exactly one trailing slash.
fn base_url(project: &Project) -> Option<String> {
    project
        .site_url
        .as_ref()
        .filter(|url| !url.is_empty())
        .map(|url| format!("{}/", url.trim_end_matches('/')))
}

/// Returns the public URL of a generated feed.
fn feed_url(project: &Project, name: &str) -> Option<String> {
    base_url(project).map(|base| format!("{base}{name}"))
}
